version: "3.4"
services:
    postgres:
        image: postgres:13.6-alpine
        environment:
            POSTGRES_USER: testsuite
            POSTGRES_PASSWORD: testsuite
        healthcheck:
            test: pg_isready

    laravel-samlidp:
        build:
            args:
                GITHUB_TOKEN: $GITHUB_TOKEN
        environment:
            APP_KEY: AckfSECXIvnK5r28GVIWUAxmbBSjTsmF
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - .:/var/www
